name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    name: Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get the full Git history

      - name: Install Gitleaks
        run: |
          wget -qO- https://github.com/gitleaks/gitleaks/releases/download/v8.28.0/gitleaks_8.28.0_linux_x64.tar.gz | tar xz
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: gitleaks dir . --verbose